gathering:
  mastery: 375
  level: "Artisan 5"
processing:
  mastery: 390
  level: "Artisan 8"
  subskills:
    shaking: 1150
    grinding: 1150
    chopping: 1150
    drying: 1150
    filtering: 1150
    heating: 1150
cooking:
  mastery: 1385
  level: "Master 15"
alchemy:
  mastery: 1235
  level: "Artisan 5"
